/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

// Import new model and auth classes
import auth.AuthManager;
import info5100.university.example.model.directory.AssignmentDirectory;
import info5100.university.example.model.directory.SubmissionDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Faculty;
import model.directory.CourseDirectory;
import model.directory.EnrollmentDirectory;
import model.directory.PersonDirectory;
import ui.CourseManagement.CourseDetailsJPanel;
import ui.CourseManagement.CourseEnrollmentJPanel;
import ui.CourseManagement.SyllabusManagementJPanel;
// We will refactor these child panels next
// import ui.CourseManagement.CourseDetailsJPanel;
// import ui.CourseManagement.SyllabusManagementJPanel;
// import ui.CourseManagement.CourseEnrollmentJPanel;

/**
 *
 * @author zenishborad
 */
public class CourseManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseManagementJPanel
     */
    private JPanel workArea; // reference to MainJFrame's workArea
    private AuthManager authManager;
    private PersonDirectory personDirectory;
    private CourseDirectory courseDirectory;
    private EnrollmentDirectory enrollmentDirectory;
    private Faculty loggedInFaculty;
    private AssignmentDirectory assignmentDirectory;
    private SubmissionDirectory submissionDirectory;

    // New constructor
    public CourseManagementJPanel(JPanel workArea, AuthManager authManager, PersonDirectory personDirectory,
                            CourseDirectory courseDirectory, EnrollmentDirectory enrollmentDirectory,
                            AssignmentDirectory assignmentDirectory, SubmissionDirectory submissionDirectory, // Added params
                            Faculty loggedInFaculty) {
    this.workArea = workArea;
    this.authManager = authManager;
    this.personDirectory = personDirectory;
    this.courseDirectory = courseDirectory;
    this.enrollmentDirectory = enrollmentDirectory;
    this.assignmentDirectory = assignmentDirectory; // Assign param
    this.submissionDirectory = submissionDirectory; // Assign param
    this.loggedInFaculty = loggedInFaculty;
    initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseDetails = new javax.swing.JButton();
        btnSyllabusManagement = new javax.swing.JButton();
        btnCourseEnrollment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnCourseDetails.setText("Course Details");
        btnCourseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseDetailsActionPerformed(evt);
            }
        });

        btnSyllabusManagement.setText("Syllabus Management");
        btnSyllabusManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyllabusManagementActionPerformed(evt);
            }
        });

        btnCourseEnrollment.setText("Course Enrollment");
        btnCourseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseEnrollmentActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCourseDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnSyllabusManagement)
                .addGap(84, 84, 84)
                .addComponent(btnCourseEnrollment)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSyllabusManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSyllabusManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyllabusManagementActionPerformed
        // TODO add your handling code here:                                                 
    // Get the logged-in user's FacultyProfile
SyllabusManagementJPanel syllabusPanel = new SyllabusManagementJPanel(workArea, loggedInFaculty, courseDirectory);
        workArea.add("SyllabusManagementJPanel", syllabusPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnSyllabusManagementActionPerformed

    private void btnCourseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseDetailsActionPerformed
        // TODO add your handling code here:
        CourseDetailsJPanel detailsPanel = new CourseDetailsJPanel(workArea, loggedInFaculty, courseDirectory, assignmentDirectory); // Pass assignmentDirectory
        workArea.add("CourseDetailsJPanel", detailsPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnCourseDetailsActionPerformed

    private void btnCourseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseEnrollmentActionPerformed
                                                  
    // Get the logged-in faculty profile
CourseEnrollmentJPanel enrollmentPanel = new CourseEnrollmentJPanel(workArea, loggedInFaculty, courseDirectory);
        workArea.add("CourseEnrollmentJPanel", enrollmentPanel); // Referring to ui.CourseManagement.CourseEnrollmentJPanel
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnCourseEnrollmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
       workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseDetails;
    private javax.swing.JButton btnCourseEnrollment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSyllabusManagement;
    // End of variables declaration//GEN-END:variables
}
