/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

// Import new model and auth classes
import auth.AuthManager;
import auth.UserAccount;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.Faculty;
import model.directory.CourseDirectory;
import model.directory.EnrollmentDirectory;
import model.directory.PersonDirectory;
// We will refactor the other panels (CourseMgmt, StudentMgmt, etc.) next
// import ui.CourseManagementJPanel;
// import ui.StudentManagementJPanel;
// import ui.PerformanceReportingJPanel;
// import ui.EnrollmentInsightJPanel;

/**
 *
 * @author zenishborad
 */
public class FacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyJPanel
     */
    private JPanel workArea; // This is the CardLayout panel from MainJFrame
    private AuthManager authManager;
    private PersonDirectory personDirectory;
    private CourseDirectory courseDirectory;
    private EnrollmentDirectory enrollmentDirectory;
    
    private Faculty loggedInFaculty; // Store the logged-in faculty member

    /**
     * New constructor to accept the central data directories and auth manager.
     */
    public FacultyJPanel(JPanel workArea, AuthManager authManager, PersonDirectory personDirectory, CourseDirectory courseDirectory, EnrollmentDirectory enrollmentDirectory) {
        this.workArea = workArea;
        this.authManager = authManager;
        this.personDirectory = personDirectory;
        this.courseDirectory = courseDirectory;
        this.enrollmentDirectory = enrollmentDirectory;
        
        // Find the logged-in Faculty object
        UserAccount currentUser = authManager.getCurrentUser();
        if (currentUser != null && "Faculty".equals(currentUser.getRole())) {
            this.loggedInFaculty = (Faculty) personDirectory.findById(currentUser.getLinkedUniversityId());
        } else {
            // This case should ideally not happen if login logic is correct
            JOptionPane.showMessageDialog(this, "Error: No valid faculty user logged in.", "Auth Error", JOptionPane.ERROR_MESSAGE);
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCourseManagement = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnEnrollmentInsight = new javax.swing.JButton();
        btnStudentManagement = new javax.swing.JButton();
        btnPerformanceReporting = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Faculty Profile");

        btnCourseManagement.setText("Course Management");
        btnCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManagementActionPerformed(evt);
            }
        });

        btnProfileManagement.setText("Profile Management");
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnEnrollmentInsight.setText("Enrollment Insight");
        btnEnrollmentInsight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollmentInsightActionPerformed(evt);
            }
        });

        btnStudentManagement.setText("Student Management");
        btnStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagementActionPerformed(evt);
            }
        });

        btnPerformanceReporting.setText("Performance Reporting");
        btnPerformanceReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportingActionPerformed(evt);
            }
        });

        btnLogout.setText("Back");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCourseManagement)
                .addGap(74, 74, 74)
                .addComponent(btnProfileManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnEnrollmentInsight)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnStudentManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPerformanceReporting)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnrollmentInsight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManagementActionPerformed
                                                 
    CourseManagementJPanel coursePanel = new CourseManagementJPanel(workArea, authManager, personDirectory, courseDirectory, enrollmentDirectory, loggedInFaculty);
        workArea.add("CourseManagementJPanel", coursePanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);


    }//GEN-LAST:event_btnCourseManagementActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         // Logout logic
        authManager.logout();
        
        // Get the top-level JFrame and close it
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.dispose();
        
        // Open a new MainJFrame (login screen)
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEnrollmentInsightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollmentInsightActionPerformed
                                                   
    JOptionPane.showMessageDialog(this, "Enrollment Insight Panel not yet refactored.");

        // --- This is what we will do next ---
        // EnrollmentInsightJPanel insightPanel = new EnrollmentInsightJPanel(workArea, enrollmentDirectory, ...);
        // workArea.add("EnrollmentInsightJPanel", insightPanel);
        // ((CardLayout) workArea.getLayout()).next(workArea);
 


    }//GEN-LAST:event_btnEnrollmentInsightActionPerformed

    private void btnStudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagementActionPerformed
                                                 
    // This will now work
        StudentManagementJPanel studentPanel = new StudentManagementJPanel(workArea, loggedInFaculty, authManager, personDirectory, courseDirectory, enrollmentDirectory);
        workArea.add("StudentManagementJPanel", studentPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnStudentManagementActionPerformed

    private void btnPerformanceReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportingActionPerformed
                                                         
    JOptionPane.showMessageDialog(this, "Performance Reporting Panel not yet refactored.");

        // --- This is what we will do next ---
        PerformanceReportingJPanel reportPanel = new PerformanceReportingJPanel(workArea, loggedInFaculty, courseDirectory, enrollmentDirectory, personDirectory);
        workArea.add("PerformanceReportingJPanel", reportPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);


    }//GEN-LAST:event_btnPerformanceReportingActionPerformed

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        // TODO add your handling code here:
      if (loggedInFaculty != null) {
            ProfileManagementJPanel profilePanel = new ProfileManagementJPanel(workArea, loggedInFaculty, authManager);
            workArea.add("ProfileManagementJPanel", profilePanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        } else {
            JOptionPane.showMessageDialog(this, "Error: Faculty profile could not be loaded.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnProfileManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseManagement;
    private javax.swing.JButton btnEnrollmentInsight;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPerformanceReporting;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnStudentManagement;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
