/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

// Import necessary classes
import auth.AuthManager;
import info5100.university.example.model.directory.AssignmentDirectory;
import info5100.university.example.model.directory.SubmissionDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Faculty;
import model.directory.CourseDirectory;
import model.directory.EnrollmentDirectory;
import model.directory.PersonDirectory;
// Import the child panels (we will refactor these next)
import ui.StudentManagement.CourseEnrollmentJPanel;
import ui.StudentManagement.StudentGradingJPanel;

/**
 *
 * @author zenishborad
 */
public class StudentManagementJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private Faculty loggedInFaculty;
    private AuthManager authManager; // Might be needed for sub-panels
    private PersonDirectory personDirectory;
    private CourseDirectory courseDirectory;
    private EnrollmentDirectory enrollmentDirectory;
    private AssignmentDirectory assignmentDirectory;
    private SubmissionDirectory submissionDirectory;


    /**
     * Creates new form StudentManagementJPanel
     */
   public StudentManagementJPanel(JPanel workArea, Faculty faculty, AuthManager authManager,
                           PersonDirectory personDirectory, CourseDirectory courseDirectory,
                           EnrollmentDirectory enrollmentDirectory, AssignmentDirectory assignmentDirectory,
                           SubmissionDirectory submissionDirectory) { // Added params
    this.workArea = workArea;
    this.loggedInFaculty = faculty;
    this.authManager = authManager;
    this.personDirectory = personDirectory;
    this.courseDirectory = courseDirectory;
    this.enrollmentDirectory = enrollmentDirectory;
    this.assignmentDirectory = assignmentDirectory; // Assign param
    this.submissionDirectory = submissionDirectory; // Assign param
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseEnrollment = new javax.swing.JButton();
        btnStudentGrading = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnCourseEnrollment.setText("Course & Enrollment");
        btnCourseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseEnrollmentActionPerformed(evt);
            }
        });

        btnStudentGrading.setText("Student Grading");
        btnStudentGrading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradingActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCourseEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(btnStudentGrading, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentGrading, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseEnrollmentActionPerformed
       // Pass necessary directories and faculty info
        CourseEnrollmentJPanel enrollmentViewPanel = new CourseEnrollmentJPanel(workArea, loggedInFaculty,
                                                                            courseDirectory, enrollmentDirectory, personDirectory,
                                                                            assignmentDirectory, submissionDirectory); // Pass new dirs
        workArea.add("StudentCourseEnrollmentJPanel", enrollmentViewPanel); // Referring to ui.StudentManagement.CourseEnrollmentJPanel
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnCourseEnrollmentActionPerformed

    private void btnStudentGradingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradingActionPerformed
        // TODO add your handling code here:
        StudentGradingJPanel gradingPanel = new StudentGradingJPanel(workArea, loggedInFaculty,
                                                                 courseDirectory, enrollmentDirectory, personDirectory,
                                                                 assignmentDirectory, submissionDirectory); // Pass new dirs
        workArea.add("StudentGradingJPanel", gradingPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnStudentGradingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseEnrollment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStudentGrading;
    // End of variables declaration//GEN-END:variables
}
