/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

// Import necessary classes
import auth.AuthManager;
import info5100.university.example.model.directory.AssignmentDirectory;
import info5100.university.example.model.directory.SubmissionDirectory;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.Student;
import model.directory.CourseDirectory;
import model.directory.EnrollmentDirectory;
import model.directory.PersonDirectory;

/**
 *
 * @author Your Name
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private AuthManager authManager;
    private PersonDirectory personDirectory;
    private CourseDirectory courseDirectory;
    private EnrollmentDirectory enrollmentDirectory;
    private Student loggedInStudent;
    private AssignmentDirectory assignmentDirectory;
    private SubmissionDirectory submissionDirectory;

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    public StudentWorkAreaJPanel(JPanel workArea, AuthManager authManager, PersonDirectory personDirectory,
                               CourseDirectory courseDirectory, EnrollmentDirectory enrollmentDirectory,
                               AssignmentDirectory assignmentDirectory, SubmissionDirectory submissionDirectory) { // Added new params
        this.workArea = workArea;
        this.authManager = authManager;
        this.personDirectory = personDirectory;
        this.courseDirectory = courseDirectory;
        this.enrollmentDirectory = enrollmentDirectory;
        this.assignmentDirectory = assignmentDirectory; // Assign new param
        this.submissionDirectory = submissionDirectory; // Assign new param

        // Get the logged-in student (logic remains the same)
        String studentId = authManager.getCurrentUser().getLinkedUniversityId();
        this.loggedInStudent = (Student) personDirectory.findById(studentId);

        if (this.loggedInStudent == null) {
             JOptionPane.showMessageDialog(this, "Error: Could not find student data.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        initComponents();
        // Set welcome message (logic remains the same)
        if (this.loggedInStudent != null) {
            lblWelcome.setText("Welcome, " + loggedInStudent.getName() + "!");
        } else {
             lblWelcome.setText("Welcome!"); // Fallback
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCourseRegistration = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();
        btnFinancials = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAssignments = new javax.swing.JButton();

        lblWelcome.setText("Welcome");

        lblTitle.setText("Student Dashboard");

        btnCourseRegistration.setText("Course Registration");
        btnCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRegistrationActionPerformed(evt);
            }
        });

        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        btnGraduationAudit.setText("Graduation Audit");
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        btnFinancials.setText("Financials");
        btnFinancials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialsActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAssignments.setText("View/Submit Assignments");
        btnAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCourseRegistration)
                            .addComponent(lblTitle)
                            .addComponent(btnTranscript)
                            .addComponent(btnGraduationAudit)
                            .addComponent(btnFinancials)
                            .addComponent(btnProfile)
                            .addComponent(btnLogout)
                            .addComponent(btnAssignments))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnCourseRegistration)
                .addGap(18, 18, 18)
                .addComponent(btnTranscript)
                .addGap(18, 18, 18)
                .addComponent(btnGraduationAudit)
                .addGap(18, 18, 18)
                .addComponent(btnFinancials)
                .addGap(18, 18, 18)
                .addComponent(btnProfile)
                .addGap(18, 18, 18)
                .addComponent(btnAssignments)
                .addGap(23, 23, 23)
                .addComponent(btnLogout)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        authManager.logout();
        // Get the top-level JFrame and close it
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.dispose();
        // Open a new MainJFrame (login screen)
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegistrationActionPerformed
        // TODO add your handling code here:
        CourseRegistrationJPanel registrationPanel = new CourseRegistrationJPanel(workArea, loggedInStudent, courseDirectory, enrollmentDirectory);
        workArea.add("CourseRegistrationJPanel", registrationPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnCourseRegistrationActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        TranscriptJPanel transcriptPanel = new TranscriptJPanel(workArea, loggedInStudent, enrollmentDirectory);
        workArea.add("TranscriptJPanel", transcriptPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        // TODO add your handling code here:
        GraduationAuditJPanel auditPanel = new GraduationAuditJPanel(workArea, loggedInStudent, enrollmentDirectory);
        workArea.add("GraduationAuditJPanel", auditPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnFinancialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialsActionPerformed
        // TODO add your handling code here:
        StudentFinancialsJPanel financialsPanel = new StudentFinancialsJPanel(workArea, loggedInStudent);
        workArea.add("StudentFinancialsJPanel", financialsPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnFinancialsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        if (loggedInStudent != null) {
            // This will now work
            StudentProfileJPanel profilePanel = new StudentProfileJPanel(workArea, loggedInStudent, authManager);
            workArea.add("StudentProfileJPanel", profilePanel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        } else {
             JOptionPane.showMessageDialog(this, "Error: Student data not loaded.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsActionPerformed
        // TODO add your handling code here:
        StudentAssignmentPanel assignmentPanel = new StudentAssignmentPanel(workArea, loggedInStudent,
                                                                         enrollmentDirectory, assignmentDirectory,
                                                                         submissionDirectory);
        workArea.add("StudentAssignmentPanel", assignmentPanel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAssignmentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignments;
    private javax.swing.JButton btnCourseRegistration;
    private javax.swing.JButton btnFinancials;
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
