/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.UserAccount;
import java.awt.CardLayout;

/**
 *
 * @author zenishborad
 */
public class FacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyJPanel
     */
    private javax.swing.JPanel workArea; // reference to MainJFrame's workArea

// New constructor that accepts workArea
private UserAccount loggedInUser;
private FacultyDirectory facultyDirectory;

public FacultyJPanel(javax.swing.JPanel workArea, UserAccount loggedInUser, FacultyDirectory facultyDirectory) {
    this.workArea = workArea;
    this.loggedInUser = loggedInUser;
    this.facultyDirectory = facultyDirectory;
    initComponents();

}

    public FacultyJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCourseManagement = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnEnrollmentInsight = new javax.swing.JButton();
        btnStudentManagement = new javax.swing.JButton();
        btnPerformanceReporting = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Faculty Profile");

        btnCourseManagement.setText("Course Management");
        btnCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManagementActionPerformed(evt);
            }
        });

        btnProfileManagement.setText("Profile Management");
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnEnrollmentInsight.setText("Enrollment Insight");
        btnEnrollmentInsight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollmentInsightActionPerformed(evt);
            }
        });

        btnStudentManagement.setText("Student Management");
        btnStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagementActionPerformed(evt);
            }
        });

        btnPerformanceReporting.setText("Performance Reporting");
        btnPerformanceReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportingActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCourseManagement)
                .addGap(74, 74, 74)
                .addComponent(btnProfileManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnEnrollmentInsight)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnStudentManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPerformanceReporting)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnrollmentInsight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManagementActionPerformed
                                                 
    workArea.removeAll();

    CourseManagementJPanel coursePanel = new CourseManagementJPanel(workArea, loggedInUser, facultyDirectory);

    workArea.add("coursePanel", coursePanel);
    ((CardLayout) workArea.getLayout()).next(workArea);

    workArea.revalidate();
    workArea.repaint();


    }//GEN-LAST:event_btnCourseManagementActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
         MainJFrame login = new MainJFrame(); // Replace with your actual login JFrame class
    login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEnrollmentInsightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollmentInsightActionPerformed
                                                   
    FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());
    Department dept = fp.getDepartment(); // get the department

    EnrollmentInsightJPanel insightPanel = new EnrollmentInsightJPanel(workArea, dept);
    workArea.add("EnrollmentInsightJPanel", insightPanel);

    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.show(workArea, "EnrollmentInsightJPanel"); // safer than next()

    workArea.revalidate();
    workArea.repaint();
 


    }//GEN-LAST:event_btnEnrollmentInsightActionPerformed

    private void btnStudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagementActionPerformed
                                                 
    workArea.removeAll();

    // Get logged-in faculty profile
    FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());

    // Pass faculty profile to StudentManagementJPanel
    StudentManagementJPanel studentPanel = new StudentManagementJPanel(workArea, fp);
    workArea.add("StudentManagementJPanel", studentPanel);
    ((CardLayout) workArea.getLayout()).next(workArea);

    workArea.revalidate();
    workArea.repaint();

    }//GEN-LAST:event_btnStudentManagementActionPerformed

    private void btnPerformanceReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportingActionPerformed
                                                         
    workArea.removeAll();

    FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());
    Department dept = fp.getDepartment(); // assuming getDepartment() exists in FacultyProfile

    PerformanceReportingJPanel reportPanel = new PerformanceReportingJPanel(workArea, fp, dept);
    workArea.add("PerformanceReportingJPanel", reportPanel);
    ((CardLayout) workArea.getLayout()).next(workArea);

    workArea.revalidate();
    workArea.repaint();


    }//GEN-LAST:event_btnPerformanceReportingActionPerformed

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        // TODO add your handling code here:
      FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());
ProfileManagementJPanel profilePanel = new ProfileManagementJPanel(workArea, fp);
workArea.add("ProfileManagementJPanel", profilePanel);
CardLayout layout = (CardLayout) workArea.getLayout();
layout.next(workArea);

    }//GEN-LAST:event_btnProfileManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseManagement;
    private javax.swing.JButton btnEnrollmentInsight;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPerformanceReporting;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnStudentManagement;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
