/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import info5100.university.example.Persona.Faculty.FacultyProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.StudentManagement.CourseEnrollmentJPanel;
import ui.StudentManagement.StudentGradingJPanel;

/**
 *
 * @author zenishborad
 */
public class StudentManagementJPanel extends javax.swing.JPanel {
    private javax.swing.JPanel workArea;
    private FacultyProfile loggedInFaculty;


    /**
     * Creates new form StudentManagementJPanel
     */
   public StudentManagementJPanel(JPanel workArea, FacultyProfile faculty) {
    this.workArea = workArea;
    this.loggedInFaculty = faculty;
    initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseEnrollment = new javax.swing.JButton();
        btnStudentGrading = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnCourseEnrollment.setText("Course & Enrollment");
        btnCourseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseEnrollmentActionPerformed(evt);
            }
        });

        btnStudentGrading.setText("Student Grading");
        btnStudentGrading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradingActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnCourseEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(btnStudentGrading, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentGrading, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseEnrollmentActionPerformed
        // TODO add your handling code here:
          CourseEnrollmentJPanel panel = new CourseEnrollmentJPanel(loggedInFaculty);
    workArea.add("CourseEnrollmentJPanel", panel);
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.next(workArea);

    }//GEN-LAST:event_btnCourseEnrollmentActionPerformed

    private void btnStudentGradingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradingActionPerformed
        // TODO add your handling code here:
        StudentGradingJPanel panel = new StudentGradingJPanel();
    workArea.add("StudentGradingJPanel", panel);
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.next(workArea);

    }//GEN-LAST:event_btnStudentGradingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseEnrollment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStudentGrading;
    // End of variables declaration//GEN-END:variables
}
