/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import info5100.university.example.Persona.Faculty.FacultyDirectory;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import ui.CourseManagement.CourseDetailsJPanel;
import ui.CourseManagement.SyllabusManagementJPanel;
import ui.CourseManagement.CourseEnrollmentJPanel;


/**
 *
 * @author zenishborad
 */
public class CourseManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseManagementJPanel
     */
    private javax.swing.JPanel workArea; // reference to MainJFrame's workArea
    private FacultyDirectory facultyDirectory;
private UserAccount loggedInUser;  // store the currently logged-in user

// New constructor
public CourseManagementJPanel(javax.swing.JPanel workArea, UserAccount loggedInUser, FacultyDirectory facultyDirectory) {
    this.workArea = workArea;
    this.loggedInUser = loggedInUser;
    this.facultyDirectory = facultyDirectory;
    initComponents();
}


    public CourseManagementJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseDetails = new javax.swing.JButton();
        btnSyllabusManagement = new javax.swing.JButton();
        btnCourseEnrollment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnCourseDetails.setText("Course Details");
        btnCourseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseDetailsActionPerformed(evt);
            }
        });

        btnSyllabusManagement.setText("Syllabus Management");
        btnSyllabusManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyllabusManagementActionPerformed(evt);
            }
        });

        btnCourseEnrollment.setText("Course Enrollment");
        btnCourseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseEnrollmentActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCourseDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnSyllabusManagement)
                .addGap(84, 84, 84)
                .addComponent(btnCourseEnrollment)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSyllabusManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSyllabusManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyllabusManagementActionPerformed
        // TODO add your handling code here:                                                 
    // Get the logged-in user's FacultyProfile
    FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());

    if (fp != null) {
        SyllabusManagementJPanel panel = new SyllabusManagementJPanel(fp);
        workArea.add("SyllabusManagementJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "SyllabusManagementJPanel");
    } else {
        JOptionPane.showMessageDialog(this, "Faculty profile not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btnSyllabusManagementActionPerformed

    private void btnCourseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseDetailsActionPerformed
        // TODO add your handling code here:
FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());
if (fp != null) {
    CourseDetailsJPanel details = new CourseDetailsJPanel(workArea, fp); // pass faculty
    workArea.add("CourseDetailsPanel", details);

    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.show(workArea, "CourseDetailsPanel");
} else {
    JOptionPane.showMessageDialog(this, "Faculty profile not found!", "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_btnCourseDetailsActionPerformed

    private void btnCourseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseEnrollmentActionPerformed
                                                  
    // Get the logged-in faculty profile
    FacultyProfile fp = facultyDirectory.findByPerson(loggedInUser.getPerson());
    if (fp != null) {
        CourseEnrollmentJPanel panel = new CourseEnrollmentJPanel(fp); // pass the profile
        workArea.add("CourseEnrollmentJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.show(workArea, "CourseEnrollmentJPanel"); // show the panel
    } else {
        JOptionPane.showMessageDialog(this, "Faculty profile not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btnCourseEnrollmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        MainJFrame login = new MainJFrame(); // Replace with your actual login JFrame class
    login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseDetails;
    private javax.swing.JButton btnCourseEnrollment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSyllabusManagement;
    // End of variables declaration//GEN-END:variables
}
