/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import java.awt.CardLayout;

/**
 *
 * @author zenishborad
 */
public class EnrollmentInsightJPanel extends javax.swing.JPanel {

     private javax.swing.JPanel workArea;
      private Department department; // add this

    /**
     * Creates new form EnrollmentInsightJPanel
     */
     public EnrollmentInsightJPanel(javax.swing.JPanel workArea, Department department) {
        this.workArea = workArea;
        this.department = department;
        initComponents();
        populateSemesterComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        btnGenerateInsight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblStudentsEnrolled = new javax.swing.JLabel();
        txtStudentsEnrolled = new javax.swing.JTextField();
        lblTotalRevenue = new javax.swing.JLabel();
        txtTotalRevenue = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        lblSemester.setText("Semester");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerateInsight.setText("Generate Insight");
        btnGenerateInsight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateInsightActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Code", "Course Name", "Students Enrolled ", "Total Revenue"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblStudentsEnrolled.setText("Total Students Enrolled");

        lblTotalRevenue.setText("Total Revenue");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemester)
                        .addGap(30, 30, 30)
                        .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(btnGenerateInsight)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentsEnrolled)
                            .addComponent(lblTotalRevenue))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txtStudentsEnrolled))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateInsight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentsEnrolled)
                    .addComponent(txtStudentsEnrolled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRevenue))
                .addGap(95, 95, 95)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateInsightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateInsightActionPerformed
        // TODO add your handling code here:                                                  
    String selectedSemester = (String) cmbSemester.getSelectedItem();
    if (selectedSemester == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a semester.");
        return;
    }

    CourseSchedule schedule = department.getMastercoursecatalog().get(selectedSemester);
    if (schedule == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No data available for selected semester.");
        return;
    }

    java.util.List<CourseOffer> offers = schedule.getSchedule();
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    int totalStudents = 0;
    int totalRevenue = 0;

    for (CourseOffer offer : offers) {
        int enrolled = (int) offer.getSeatlist().stream().filter(s -> s.isOccupied()).count();
        int revenue = offer.getTotalCourseRevenues();

        model.addRow(new Object[]{
            offer.getCourseNumber(),
            offer.getSubjectCourse().getName(),
            enrolled,
            "$" + revenue
        });

        totalStudents += enrolled;
        totalRevenue += revenue;
    }

    txtStudentsEnrolled.setText(String.valueOf(totalStudents));
    txtTotalRevenue.setText("$" + totalRevenue);

    }//GEN-LAST:event_btnGenerateInsightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateInsight;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblStudentsEnrolled;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTextField txtStudentsEnrolled;
    private javax.swing.JTextField txtTotalRevenue;
    // End of variables declaration//GEN-END:variables

   private void populateSemesterComboBox() {
    cmbSemester.removeAllItems();
    for (String semester : department.getMastercoursecatalog().keySet()) {
        cmbSemester.addItem(semester);
    }
}

}
